#!/bin/bash

echo "Enter an alphabet"
read alphabet

case $alphabet in
a) echo "It is a vowel"
;;
e) echo "It is a vowel"
;;
i) echo "It is a vowel"
;;
o) echo "It is a vowel"
;;
u) echo "It is a vowel"
;;
*) echo "It is not a vowel"
;;
esac
